[package]
name = "ark_prover_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-circom = "0.5.0"
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-std = "0.5.0"
ark-relations = "0.5.0"
ark-groth16 = "0.5.0"
ark-snark = "0.5.0"
ark-bls12-381 = "0.5.0"
num-bigint = { version = "0.4.3", features = ["serde"] }
num-traits = "0.2.17"
color-eyre = "0.6.2"
once_cell = "1.18.0"
